# Generated by Django 4.0.1 on 2022-04-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='Room',
        ),
    ]
