tours = [
    {
        '_id': '1',
        'name': 'Santorini',
        'image': '/images/santorini.jpg',
        'description': 'Santorini is the southernmost island of Cyclades and is located between Ios and Anafi. It is 128 nautical miles away from the port of Piraeus and 63 nautical miles away from Crete.',
        'category': 'Islands',
        'price': 99.99,
        'available': 1,
        'rating': 4.8,
        'numReviews': 28,
    },
    {
        '_id': '2',
        'name': 'Nestos River',
        'image': '/images/nestos.jpg',
        'description': 'The famous Delta of Nestos occupies a large area in the southern sections of the prefectures of Kavala and Xanthi. The point where the river meets the sea is a place of intense interest for naturalists, and therefore attracts lots of visitors. The Delta of Nestos has been acclaimed a Wetland of International Significance, and is protected by the Ramsar Convention.',
        'category': 'Rivers',
        'price': 49.99,
        'available': 1,
        'rating': 2.8,
        'numReviews': 12,
    },
    {
        '_id': '3',
        'name': 'Meteora',
        'image': '/images/meteora.jpg',
        'description': 'Meteora today is the largest archaeological site of Greece in terms of the area that it covers. It is also a UNESCO World Heritage Site since 1989',
        'category': 'Special',
        'price': 69.99,
        'available': 0,
        'rating': 4.7,
        'numReviews': 22,
    },
    {
        '_id': '4',
        'name': 'Samothrace',
        'image': '/images/samothrace.jpg',
        'description': 'Samothrace, Modern Greek Samothráki, Greek island in the northern Aegean Sea off the Thracian coast. It forms a dímos (municipality) in the East Macedonia and Thrace (Modern Greek: Anatolikí Makedonía kai Thrakí) periféreia (region). The island is geologically complex, consisting chiefly of ancient granites, clayey deposits, and softer volcanic materials.',
        'category': 'Islands',
        'price': 49.99,
        'available': 0,
        'rating': 4.9,
        'numReviews': 32,
    },
    {
        '_id': '5',
        'name': 'Mt.Olympos',
        'image': '/images/olympos.jpg',
        'description': 'Mount Olympus, in north east Greece, has been known as the home of Zeus and the major Greek gods since before the time of Homer. The semi-legendary author of the Odyssey and the Iliad, who may have lived any time between 800 and 1200 years before Christ, included this dramatic mountain in his stories of the gods and as the source of thunderbolts from Zeus.',
        'category': 'Mountains',
        'price': 59.99,
        'available': 1,
        'rating': 4.7,
        'numReviews': 32,
    },
    {
        '_id': '6',
        'name': 'Zagorochoria',
        'image': '/images/zagorochoria.jpg',
        'description': 'Zagorochoria Greece is a complex of mountainous villages located on the north-western side of the country, in the Epirus region. Zagorochoria villages look like postcards! Made up of traditional stone-made houses, narrow alleys and grey-tiled roofs, the villages of Zagorochoria ooze charm in abundance. This incredibly beautiful region is still untouched by international tourists, so it is a perfect holiday destination off the beaten tourist trail.',
        'category': 'Mountains',
        'price': 49.99,
        'available': 0,
        'rating': 4.6,
        'numReviews': 32,
    },
    {
        '_id': '7',
        'name': 'Kerkini Lake',
        'image': '/images/kerkini.jpg',
        'description': 'Artificial lake Kerkini. 21/08/75; Serres; Added to the Montreux Record, 4 July 1990, removed from the Record, 18 May 1999. Special Protection Area EC Directive; No Hunting Zone.Near the border between Greece, Bulgaria and the former Yugoslavia, an nutrient-rich, freshwater reservoir in an alluvial plain between mountain massifs, supporting extensive beds of floating vegetation and subject to wide variations in water level.',
        'category': 'Lakes',
        'price': 39.99,
        'available': 1,
        'rating': 4.3,
        'numReviews': 14,
    },
    {
        '_id': '8',
        'name': 'Rhodes Old City',
        'image': '/images/rhodes.jpg',
        'description': 'In the Medieval - Old - Town of Rhodes one may for sure enjoy one of the most interesting walks on the island. Do not let the "medieval" mislead you: rather than a ruined, deserted setting, you will be pleasantly surprised to wander through an intricate network of busy little commercial streets delightfully alternating with quiet alleys, in what is a very much alive town consistently dwelt in over the last two thousand years!  No wonder, therefore, that for some time now, the Medieval Quarter of Rhodes - the oldest inhabited medieval town in Europe - forms part of the UNESCO World Cultural Heritage network!',
        'category': 'Towns',
        'price': 49.99,
        'available': 1,
        'rating': 4.1,
        'numReviews': 54,
    },
]
