# Generated by Django 4.0.1 on 2022-04-16 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userFirstName', models.CharField(max_length=50)),
                ('userLastName', models.CharField(max_length=50)),
                ('user_registration', models.DateField()),
                ('userDateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guideFirstName', models.CharField(max_length=50)),
                ('guideLastName', models.CharField(max_length=50)),
                ('guideDescription', models.CharField(max_length=300)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('numberOfActivities', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('avgRating', models.IntegerField(blank=True, null=True)),
                ('isGuideApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TourExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tourTitle', models.CharField(max_length=100)),
                ('tourLocation', models.CharField(max_length=50)),
                ('tourDuration', models.IntegerField()),
                ('tourPrice', models.FloatField()),
                ('tourAvailableDate', models.DateField()),
                ('tourMaxNumberOfPeople', models.IntegerField()),
                ('tourDescription', models.TextField(max_length=499)),
                ('tourImage', models.ImageField(null=True, upload_to='static/media/images/')),
                ('tourGuide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tourguide')),
            ],
        ),
    ]
