# Generated by Django 4.0.1 on 2022-04-17 16:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('guideDescription', models.CharField(max_length=300)),
                ('numberOfActivities', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('isGuideApproved', models.CharField(choices=[('Approved', True), ('Non-approved', False)], max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TourExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourTitle', models.CharField(max_length=100)),
                ('tourLocation', models.CharField(max_length=50)),
                ('tourDuration', models.IntegerField()),
                ('tourPrice', models.FloatField()),
                ('tourAvailableDate', models.DateField()),
                ('tourMaxNumberOfPeople', models.IntegerField()),
                ('tourDescription', models.TextField(max_length=499)),
                ('tourImage', models.ImageField(null=True, upload_to='static/media/images/')),
                ('tourGuide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourexperience', to='main_app.tourguide')),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userDateOfBirth', models.DateField()),
                ('tourExperiences', models.ManyToManyField(to='main_app.TourExperience')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
