# Generated by Django 4.0.1 on 2022-04-18 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orderDetail',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.orderdetail'),
        ),
    ]
