# Generated by Django 4.0.3 on 2022-04-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourexperience',
            name='tourBookings',
            field=models.IntegerField(default=0, verbose_name='Tour Bookings'),
        ),
    ]
