# Generated by Django 4.0.3 on 2022-04-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourexperience',
            options={'verbose_name': 'TourExperience'},
        ),
        migrations.AlterField(
            model_name='tourexperience',
            name='endUser',
            field=models.ManyToManyField(blank=True, related_name='tourExperiences', to='main_app.enduser'),
        ),
        migrations.AlterField(
            model_name='tourexperience',
            name='tourGuide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.tourguide'),
        ),
    ]
