# Generated by Django 4.0.3 on 2022-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='userDateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
