# Generated by Django 4.0.3 on 2022-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourDescription',
            field=models.TextField(max_length=500, verbose_name='Tour Description'),
        ),
    ]
