# Generated by Django 4.0.4 on 2022-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Tour Image'),
        ),
    ]
