# Generated by Django 4.0.3 on 2022-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='isGuideApproved',
            field=models.CharField(choices=[(True, 'Approved'), (False, 'Non-approved')], max_length=12),
        ),
    ]
