# Generated by Django 4.0.3 on 2022-04-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_enduser_userdateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/'),
        ),
    ]
