# Generated by Django 4.0.1 on 2022-04-21 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tourexperience_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourexperience',
            name='tourRating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Tour Rating'),
            preserve_default=False,
        ),
    ]
