# Generated by Django 4.0.3 on 2022-04-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tourexperience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.enduser')),
                ('tourExperience', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.tourexperience')),
            ],
        ),
    ]
