# Generated by Django 4.0.3 on 2022-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_enduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourexperience',
            name='tourImage',
            field=models.ImageField(null=True, upload_to='static/media/images/'),
        ),
    ]
