# Generated by Django 4.0.3 on 2022-04-22 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tourexperience_tourrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourRating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Tour Rating'),
        ),
    ]
