# Generated by Django 4.0.3 on 2022-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_tourexperience_tourrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourCategory',
            field=models.CharField(choices=[('Food Experience', 'food_experience'), ('Activities in Nature', 'activities_in_nature'), ('Drinking experience', 'drinking_experience'), ('Spiritual experience', 'spiritual_experience'), ('Sightseeing experience', 'sightseeing_experience')], max_length=50),
        ),
    ]
