# Generated by Django 4.0.3 on 2022-04-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_orderdetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='userEmail',
        ),
    ]
