# Generated by Django 4.0.3 on 2022-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_tourexperience_tourcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='seller_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Seller Email'),
        ),
    ]
