# Generated by Django 4.0.3 on 2022-04-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_enduser_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name='Customer Email'),
        ),
    ]
