# Generated by Django 4.0.3 on 2022-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_tourexperience_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourexperience',
            name='tourDescription',
            field=models.TextField(max_length=499),
        ),
    ]
